version: "3.3"
services:
  db:
    container_name: db_container
    image: postgres
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=P@ssw0rd
      - POSTGRES_DB=myshop
    volumes:
      - pgdata:/var/lib/postgresql/data/

  api:
    container_name: api-container
    build: ./api
    #command: uwsgi --ini uwsgi.ini
    command: sh -c "wait-for db:5432 && python manage.py migrate && uwsgi --ini uwsgi.ini"
    volumes:
      - api:/usr/src/app
    depends_on:
      - db
    #ports:
    #  - 8000:8000

  nginx:
    container_name: nginx_container
    build: ./nginx
    ports:
      - 80:80
    volumes:
      - api:/usr/src/app

  celery:
    container_name: celery_container
    build: ./api
    volumes:
      - api:/usr/src/app
    command: celery -A docker_django_tutorial worker -l INFO -Q dev
    depends_on:
      - db
      - api
    
  # scheduler:
  #   container_name: scheduler_container
  #   build: ./api
  #   volumes:
  #     - api:/usr/src/app
  #   command: celery -A docker_django_tutorial beat -l INFO
 
volumes:
  api:
  pgdata:
